apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: your-nodejs-image:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: node-app-config
            - secretRef:
                name: node-app-secrets
          volumeMounts:
            - name: app-storage
              mountPath: /app/storage
      volumes:
        - name: app-storage
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-app-config
data:
  # Add your configuration key-value pairs here
  DATABASE_URL: your-database-url
  API_KEY: your-api-key
---
apiVersion: v1
kind: Secret
metadata:
  name: node-app-secrets
type: Opaque
data:
  # Add your secret key-value pairs here (base64-encoded)
  SECRET_KEY: TXlMb3ZlUG9vbmFtCg==
