apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: us-central1-docker.pkg.dev/linear-stock-388107/noderegistry/nodeapp:1.0
        ports:
        - containerPort: 8080
