apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodeapp-pv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-pv
    fsType: ext4
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  labels:
    app: app
spec:
  storageClassName: standard
  volumeName: nodeapp-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce