apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: app
type: Opaque
data:
  # Add your secret key-value pairs here (base64-encoded)
  DB_USER: dXNlcjEK
  DB_PASSWORD: cGFzc3dvcmQxCg==